org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=delightlib
mod_name=Delight Lib
mod_license=MIT
mod_version=26.05.18-26.1-fabric
mod_authors=Axperty
mod_description=A library mod for Farmer's Delight that aims to make other add-ons easily.
maven_group=com.axperty
archives_base_name=delightlib

# Dependencies
fabric_api_version=0.152.2+26.2